; -----------------------------------------------------------------------------
; Code 117 - Acura, Alba, Amstrad, Anitech, Basic Line, Bush, Cascade, Cimline,
; Contec, Crown, Daewoo, Daytron, Dixi, Elta, Firstline, Geloso, HCM, Hinari,
; Kaisui, Koyoda, M Electronic, Matsui, Memorex, Multitech, Pausa, Profex,
; Protech, Roadstar, Saisho, Samsung, Sonoko, Standard, Teletech

; Carrier Freq = 37.47 KHz
.db (((XTAL / 37470.0) / 2.0) - 1.0), 53

.db 16, 8 // 868      427
.db 1, 1 // 53       53
.db 1, 3 // 53      161
.db 1, 1 // 53       53
.db 1, 1 // 53       53
.db 1, 1 // 53       53
.db 1, 1 // 53       53
.db 1, 1 // 53       53
.db 1, 1 // 53       53
.db 1, 8 // 53      428
.db 1, 1 // 53       53
.db 1, 3 // 53      161
.db 1, 3 // 53      161
.db 1, 3 // 53      161
.db 1, 1 // 53       53
.db 1, 1 // 53       53
.db 1, 1 // 53       53
.db 1, 1 // 53       53
.db 1, 47 // 53     2507
.db 16, 8 // 868      428
.db 1, 1 // 53       53
.db 1, 3 // 53      161
.db 1, 1 // 53       53
.db 1, 1 // 53       53
.db 1, 1 // 53       53
.db 1, 1 // 53       53
.db 1, 1 // 53       53
.db 1, 1 // 53       53
.db 1, 8 // 53      428
.db 1, 1 // 53       53
.db 1, 3 // 53      161
.db 1, 3 // 53      161
.db 1, 3 // 53      161
.db 1, 1 // 53       53
.db 1, 1 // 53       53
.db 1, 1 // 53       53
.db 1, 1 // 53       53
.db 1, 0 // 52       0
